services:
  - type: web
    name: web-entregas
    env: node
    buildCommand: |
      corepack enable
      corepack prepare yarn@4.8.1 --activate
      yarn set version 4.8.1
      yarn install --mode=update-lockfile
      yarn build
    startCommand: yarn preview
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: YARN_VERSION
        value: 4.8.1 